export const state = () => ({
  list: [{
      id: 'P001',
      name: 'Apsara Selections for Nusountara',
      slug: 'apsara-selections',
      artist: 'Apsara',
      artist_slug: 'apsara',
      cover_image: 'apsara-selections.webp',
      songs: [{
          id: '001',
          title: 'Energetic Stability - Vanita Remix',
          slug: 'energetic-stability',
          description: '',
          artist: 'Jeancy, Vanita',
          album: 'Inner Awen Vol. IV',
          playlist: 'Apsara Selections for Nusountara',
          cover_image: 'energetic-stability.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/7zMpjwJXj3tDOuKYfHYXV9?utm_source=generator&theme=0',
          link: {
            spotify: 'https://open.spotify.com/track/7zMpjwJXj3tDOuKYfHYXV9?si=96ebf169c2344016',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '002',
          title: 'Hybrid Society',
          slug: 'hybrid-society',
          description: '',
          artist: 'Matthias Meyer, Budakid',
          album: 'Sweet Ease / Hybrid Society',
          playlist: 'Apsara Selections for Nusountara',
          cover_image: 'hybrid-society.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/36UcjzLY5OC9Zhh8wIxobk?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/36UcjzLY5OC9Zhh8wIxobk?si=4586471d608a44af',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '003',
          title: 'Isolated',
          slug: 'isolated',
          description: '',
          artist: 'Zalvador',
          album: 'Isolated',
          playlist: 'Apsara Selections for Nusountara',
          cover_image: 'isolated.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/2TsoBkPWVBYZIoLAeJKOsD?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/2TsoBkPWVBYZIoLAeJKOsD?si=1fb1e4cf7d06429d',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '004',
          title: 'Manolito - Mixed',
          slug: 'manolito-mixed',
          description: '',
          artist: 'Marc DePulse',
          album: 'Ian Ludvig',
          playlist: 'Apsara Selections for Nusountara',
          cover_image: 'manolito-mixed.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/43X9vPylgkBqyN5Fo12bqo?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/43X9vPylgkBqyN5Fo12bqo?si=7083463b5c4b4ecc',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '005',
          title: 'Codetta - Original Mix',
          slug: 'codetta',
          description: '',
          artist: 'Ian Ludvig',
          album: 'Out of Time',
          playlist: 'Apsara Selections for Nusountara',
          cover_image: 'codetta.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/76aNLKn7Vx1ylDmcYrBitH?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/76aNLKn7Vx1ylDmcYrBitH?si=156da922aa31471f',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '006',
          title: 'Two Steps Ahead',
          slug: 'two-steps-ahead',
          description: '',
          artist: 'CJ Jeff, Robert Owens',
          album: 'Two Steps Ahead',
          playlist: 'Apsara Selections for Nusountara',
          cover_image: 'two-steps-ahead.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/7mjFKeu3WsafOkDecS0AVL?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/7mjFKeu3WsafOkDecS0AVL?si=68e382d07c6247d9',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '007',
          title: 'Alea',
          slug: 'alea',
          description: '',
          artist: 'Coeus',
          album: 'Alea',
          playlist: 'Apsara Selections for Nusountara',
          cover_image: 'alea.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/7u7ZbUU8SdNVlCQUNnt5Vn?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/7u7ZbUU8SdNVlCQUNnt5Vn?si=63419a3ee37b44b8',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '008',
          title: 'Axiom - Mixed',
          slug: 'axiom',
          description: '',
          artist: 'Erhan Kesen',
          album: 'THIS IS HOW WE DANTZE',
          playlist: 'Apsara Selections for Nusountara',
          cover_image: 'axiom.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/7ee6zNJRwQqxa9DNwiq7eo?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/7ee6zNJRwQqxa9DNwiq7eo?si=7870a44ab13842ae',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '009',
          title: 'Cordial',
          slug: 'cordial',
          description: '',
          artist: 'Arnas D, Lake Avalon',
          album: 'Stil vor Talent 300, Pt. 1',
          playlist: 'Apsara Selections for Nusountara',
          cover_image: 'cordial.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/3BHwBivzXUpmw3oaxXy56c?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/3BHwBivzXUpmw3oaxXy56c?si=8cce79bd71954a83',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '010',
          title: 'Clocks',
          slug: 'clocks',
          description: '',
          artist: 'Adana Twins, Kraków Loves Adana',
          album: '1983',
          playlist: 'Apsara Selections for Nusountara',
          cover_image: 'clocks.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/4DHrmGKXFNXQsprnIB7i2M?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/4DHrmGKXFNXQsprnIB7i2M?si=7325e7a89bf148ef',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '011',
          title: 'Korrado',
          slug: 'korrado',
          description: '',
          artist: 'Matador',
          album: 'Kingswing',
          playlist: 'Apsara Selections for Nusountara',
          cover_image: 'korrado.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/3l01TC0GrUnZAZvazUjYYz?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/3l01TC0GrUnZAZvazUjYYz?si=2f512b14a2a0449a',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '012',
          title: 'Ringo - Original Mix',
          slug: 'ringo',
          description: '',
          artist: 'Joris Voorn',
          album: 'Armada Chill 001',
          playlist: 'Apsara Selections for Nusountara',
          cover_image: 'ringo.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/6hjLUtZDHJ5GSDXwuMVJpr?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/6hjLUtZDHJ5GSDXwuMVJpr?si=59bd558826304028',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '013',
          title: 'Go',
          slug: 'go',
          description: '',
          artist: 'Moby',
          album: 'Moby',
          playlist: 'Apsara Selections for Nusountara',
          cover_image: 'go.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/6bzV0xGO4dROmmL9GmVkjM?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/6bzV0xGO4dROmmL9GmVkjM?si=0c85e2758c4047f2',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '014',
          title: 'After Dark',
          slug: 'after-dark',
          description: '',
          artist: 'Apsara',
          album: 'After Dark',
          playlist: 'Apsara Selections for Nusountara',
          cover_image: 'after-dark.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/5RXktsjbcCo4oxh8jIsCG5?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/5RXktsjbcCo4oxh8jIsCG5?si=4595a1320f4b45eb',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '015',
          title: 'Leap Year',
          slug: 'leap-year',
          description: '',
          artist: 'Steve Self',
          album: 'Shutter Shadow',
          playlist: 'Apsara Selections for Nusountara',
          cover_image: 'leap-year.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/0w7VZpWbF029Fe1R7KLjpC?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/0w7VZpWbF029Fe1R7KLjpC?si=44bc3a67c8b54dbd',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '016',
          title: 'Global Illumination',
          slug: 'global-illumination',
          description: '',
          artist: 'Liquid Soul',
          album: 'Love in Stereo',
          playlist: 'Apsara Selections for Nusountara',
          cover_image: 'global-illumination.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/5pGJCUcJPFDu9JO62t676u?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/5pGJCUcJPFDu9JO62t676u?si=9bb0d0768bf44a62',
          },
          created_at: new Date(2021, 9, 17),
        },
      ],
    },
    {
      id: 'P002',
      name: 'Nandi Selections for Nusountara',
      slug: 'nandi-selections',
      artist: 'Nandi',
      artist_slug: 'nandi',
      cover_image: 'nandi-selections.webp',
      songs: [{
          id: '017',
          title: 'Carnaval - Superpitcher Main Fix',
          slug: 'carnaval-superpitcher',
          description: '',
          artist: 'STUDIO MULE, Superpitcher',
          album: 'Carnaval Superpitcher Remixes',
          playlist: 'Nandi Selections for Nusountara',
          cover_image: 'carnaval-superpitcher.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/4sphhYvjapufTnaEtNzmeM?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/4sphhYvjapufTnaEtNzmeM?si=a09d197abc714de6',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '018',
          title: 'Deichkind - Autonom - Dixon Edit',
          slug: 'deichkind-autonom',
          description: '',
          artist: 'Dixon',
          album: 'Deichkind - Autonom - Dixon Edit',
          playlist: 'Nandi Selections for Nusountara',
          cover_image: 'deichkind-autonom.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/7wkwJ9b1MD6KWJxn1Hmfct?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/7wkwJ9b1MD6KWJxn1Hmfct?si=f990c3d772a04cdb',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '019',
          title: 'Trans Afro Express - Instrumental',
          slug: 'trans-afro-express',
          description: '',
          artist: 'Jerome Sydenham, Fatima Njai, Mario Punchard',
          album: 'Trans Afro Express',
          playlist: 'Nandi Selections for Nusountara',
          cover_image: 'trans-afro-express.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/372dFgiZm21u1kkqfDlfmj?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/372dFgiZm21u1kkqfDlfmj?si=affd97313359416c',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '020',
          title: 'Alcatraz - Jimpster Dub',
          slug: 'alcatraz-jimpster-dub',
          description: '',
          artist: 'Kasper Bjørke, Jacob Bellens, Jimpster',
          album: 'Alcatraz',
          playlist: 'Nandi Selections for Nusountara',
          cover_image: 'alcatraz-jimpster-dub.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/4z0WPGHhXDzBXlzIRf4ZCS?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/4z0WPGHhXDzBXlzIRf4ZCS?si=329346e26ed54665',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '021',
          title: 'Cute & Freaky - Archie Hamilton Remix',
          slug: 'cute-and-freaky',
          description: '',
          artist: 'AJ Christou, Archie Hamilton',
          album: 'Cute & Freaky',
          playlist: 'Nandi Selections for Nusountara',
          cover_image: 'cute-and-freaky.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/3ES2ENCNr0gc9pgZSujShx?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/3ES2ENCNr0gc9pgZSujShx?si=deefcb35e91b49e3',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '022',
          title: 'Erotic Soul - Sensoreal Remix',
          slug: 'erotic-soul',
          description: '',
          artist: 'Gorge, Sensoreal',
          album: 'Erotic Soul 2020',
          playlist: 'Nandi Selections for Nusountara',
          cover_image: 'erotic-soul.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/6hdBZ3ncmfDY3gXAsj1Xea?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/6hdBZ3ncmfDY3gXAsj1Xea?si=62c0799b92fc4f0c',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '023',
          title: 'Introspection - Nick Curly Remix',
          slug: 'introspection',
          description: '',
          artist: 'Audiojack, Polarbear (UK), Nick Curly',
          album: 'Introspection',
          playlist: 'Nandi Selections for Nusountara',
          cover_image: 'introspection.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/1um2IN9kPFAXubWI2gOka8?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/1um2IN9kPFAXubWI2gOka8?si=4eda763b3b574167',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '024',
          title: 'Keeping Me Up',
          slug: 'keeping-me-up',
          description: '',
          artist: '9th House',
          album: 'Keeping Me Up',
          playlist: 'Nandi Selections for Nusountara',
          cover_image: 'keeping-me-up.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/7aaiDHS4bKCWF68WG5w4RY?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/7aaiDHS4bKCWF68WG5w4RY?si=fe486551a7a34984',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '025',
          title: 'How\'s The Music - (Go Higher Mix) [Harry Romero Edit]',
          slug: 'hows-the-music',
          description: '',
          artist: 'Winx, Josh Wink',
          album: 'How\'s The Music - (Go Higher Mix) [Harry Romero Edit]',
          playlist: 'Nandi Selections for Nusountara',
          cover_image: 'hows-the-music.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/5UMeRnwkZVlA65g2OY6JWU?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/5UMeRnwkZVlA65g2OY6JWU?si=16b17e3ffc284756',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '026',
          title: 'Træns 4',
          slug: 'traen-4',
          description: '',
          artist: 'Prins Thomas',
          album: 'Træns',
          playlist: 'Nandi Selections for Nusountara',
          cover_image: 'traen-4.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/1oKzJFNfc3kzKlLze71vqx?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/1oKzJFNfc3kzKlLze71vqx?si=50ab78cdb3ec459e',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '027',
          title: 'Omnibus',
          slug: 'omnibus',
          description: '',
          artist: 'Henrik Schwarz',
          album: 'Together EP',
          playlist: 'Nandi Selections for Nusountara',
          cover_image: 'omnibus.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/3cG82yEZda7ISsAz4ww8Wn?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/3cG82yEZda7ISsAz4ww8Wn?si=66d8d3e5ae0748b4',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '028',
          title: 'Can You Feel It',
          slug: 'can-you-feel-it',
          description: '',
          artist: 'Mr. Fingers',
          album: 'Four Most Cuts Presents - Mr. Fingers',
          playlist: 'Nandi Selections for Nusountara',
          cover_image: 'can-you-feel-it.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/5BK37zwHDS5UvE3Yh0JO8n?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/5BK37zwHDS5UvE3Yh0JO8n?si=db3b219637fb4504',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '029',
          title: 'I\'ll Be Your Friend - Original Mix (2011 Remastered Version)',
          slug: 'ill-be-your-friend',
          description: '',
          artist: 'Robert Owens',
          album: 'I\'ll Be Your Friend',
          playlist: 'Nandi Selections for Nusountara',
          cover_image: 'ill-be-your-friend.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/5SMnHUNB2iBm3rkuoHpIZO?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/5SMnHUNB2iBm3rkuoHpIZO?si=af047ca917a44a0a',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '030',
          title: 'Move Your Body',
          slug: 'move-your-body',
          description: '',
          artist: 'Marshall Jefferson, Solardo',
          album: 'Move Your Body',
          playlist: 'Nandi Selections for Nusountara',
          cover_image: 'move-your-body.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/3YXIVMQLRRq2K7kxC7UYx6?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/3YXIVMQLRRq2K7kxC7UYx6?si=dd0cea5f65124044',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '031',
          title: 'Acid Tracks - 12" Version',
          slug: 'acid-tracks',
          description: '',
          artist: 'Phuture',
          album: 'Acid Tracks (Remastered)',
          playlist: 'Nandi Selections for Nusountara',
          cover_image: 'acid-tracks.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/5ga953YTjaurkXuGHFjrNk?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/5ga953YTjaurkXuGHFjrNk?si=980d5e9c2cd146cd',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '032',
          title: 'Your Love (feat. Jamie Principle)',
          slug: 'your-love',
          description: '',
          artist: 'Frankie Knuckles, Jamie Principle',
          album: 'Four Most Cuts Presents',
          playlist: 'Nandi Selections for Nusountara',
          cover_image: 'your-love.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/6tvtFyEdNpeurBkT2zNMEL?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/6tvtFyEdNpeurBkT2zNMEL?si=cab2787f22ed4594',
          },
          created_at: new Date(2021, 9, 17),
        },
        {
          id: '033',
          title: 'The Bounce',
          slug: 'the-bounce',
          description: '',
          artist: 'KenLou',
          album: 'II: The Bounce / Gimme Groove',
          playlist: 'Nandi Selections for Nusountara',
          cover_image: 'the-bounce.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/30y6AIWDz0xop8Vtfn2EyM?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/30y6AIWDz0xop8Vtfn2EyM?si=135342a850034ff9',
          },
          created_at: new Date(2021, 9, 17),
        },
      ]
    },
    {
      id: 'P003',
      name: 'Melodic House Selections for Nusountara',
      slug: 'melodic-house-selections',
      artist: 'Melodic House',
      cover_image: 'melodic-house-selections.webp',
      songs: [{
          id: '034',
          title: 'The Damned - 2021 Raw Edit',
          slug: 'the-damned',
          description: '',
          artist: 'Baime',
          album: 'The Damned (Remixed)',
          playlist: 'Melodic House Selections for Nusountara',
          cover_image: 'the-damned.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/0bJnPgVQahV5MwMGHdq4WH?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/0bJnPgVQahV5MwMGHdq4WH?si=d6a9543ac1a94679',
          },
          created_at: new Date(2021, 9, 20),
        },
        {
          id: '035',
          title: 'Shimmer',
          slug: 'shimmer',
          description: '',
          artist: 'Groovetique, Prove Them Wrong',
          album: 'Sands of Time',
          playlist: 'Melodic House Selections for Nusountara',
          cover_image: 'shimmer.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/4Uet0CtqZex6iZmTKwWyKT?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/4Uet0CtqZex6iZmTKwWyKT?si=0b94704e771d4c51',
          },
          created_at: new Date(2021, 10, 12),
        },
        {
          id: '036',
          title: 'Enigma',
          slug: 'enigma',
          description: '',
          artist: 'Moonwalk',
          album: 'Solaris - EP',
          playlist: 'Melodic House Selections for Nusountara',
          cover_image: 'enigma.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/3RhoJBbU3aXy4hO9cFQZEL?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/3RhoJBbU3aXy4hO9cFQZEL?si=4b3681febd7e4dc7',
          },
          created_at: new Date(2021, 10, 12),
        },
        {
          id: '037',
          title: 'Space Odyssey',
          slug: 'space-odyssey',
          description: '',
          artist: 'Pavel Khvaleev',
          album: 'Space Odyssey',
          playlist: 'Melodic House Selections for Nusountara',
          cover_image: 'space-odyssey.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/0tWJ9VRKIjuJrsiTbBhMhi?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/0tWJ9VRKIjuJrsiTbBhMhi?si=484ece21017248a2',
          },
          created_at: new Date(2021, 10, 12),
        },
      ]
    },
    {
      id: 'P004',
      name: 'Future Bass Selections',
      slug: 'future-bass-selections',
      artist: '',
      cover_image: 'future-bass-selections.webp',
      songs: [{
          id: '038',
          title: 'Mercy Falls',
          slug: 'mercy-falls',
          description: '',
          artist: 'CharlestheFirst',
          album: 'The Reach EP',
          playlist: 'Future Bass Selections',
          cover_image: 'mercy-falls.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/6oSxm8jKgVbrlKo4Ktd1qr?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/6oSxm8jKgVbrlKo4Ktd1qr?si=c976d01e125842b6',
          },
          created_at: new Date(2021, 10, 11),
        },
        {
          id: '043',
          title: 'Dark Crystal - Pigeon Hole Remix',
          slug: 'dark-crystal',
          description: '',
          artist: 'Minnesota, Pigeon Hole',
          album: 'Curio Remixes',
          playlist: 'Future Bass Selections',
          cover_image: 'dark-crystal.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/1YJF87L1gBY6vpiOQGUaX5?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/1YJF87L1gBY6vpiOQGUaX5?si=7165454a21244acb',
          },
          created_at: new Date(2021, 10, 12),
        },
        {
          id: '044',
          title: 'Oni',
          slug: 'oni',
          description: '',
          artist: 'Champagne Drip',
          album: 'Of Course I Still Love You',
          playlist: 'Future Bass Selections',
          cover_image: 'oni.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/2YonNPsOfBszCc1UvVCdn7?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/2YonNPsOfBszCc1UvVCdn7?si=320d0d9b5fbb4b74',
          },
          created_at: new Date(2021, 10, 12),
        },
        {
          id: '045',
          title: 'Kaleidoscope (Feat. Crystalline)',
          slug: 'kaleidoscope',
          description: '',
          artist: 'Champagne Drip, Crystalline',
          album: 'Starman',
          playlist: 'Future Bass Selections',
          cover_image: 'kaleidoscope.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/10dLRZ7GCIXEuUuONkNcxI?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/10dLRZ7GCIXEuUuONkNcxI?si=0231dda19dfd408e',
          },
          created_at: new Date(2021, 10, 12),
        },
        {
          id: '046',
          title: 'Hmu (feat. Clay Parnell & Rory \"Sweet Boy\" Dolan)',
          slug: 'hmu',
          description: '',
          artist: 'Space Jesus, Clay Parnell, Rory \"Sweet Boy\" Dolan',
          album: 'Atom + Eve',
          playlist: 'Future Bass Selections',
          cover_image: 'hmu.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/5F3t5WgLyBX2W7un8IXiLD?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/5F3t5WgLyBX2W7un8IXiLD?si=0ad5a2ddd65e4ceb',
          },
          created_at: new Date(2021, 10, 12),
        },
        {
          id: '047',
          title: 'Speaking in Tongues',
          slug: 'speaking-in-tongues',
          description: '',
          artist: 'Jade Cicada',
          album: 'Brood VII',
          playlist: 'Future Bass Selections',
          cover_image: 'speaking-in-tongues.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/1eMMDk4yBBNuxyqSINu6ti?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/1eMMDk4yBBNuxyqSINu6ti?si=b2b246a14c364af4',
          },
          created_at: new Date(2021, 10, 12),
        },
        {
          id: '048',
          title: 'Humanoid 2.0',
          slug: 'humanoid-2-0',
          description: '',
          artist: 'Eprom, ZEKE BEATS',
          album: 'Humanoid 2.0',
          playlist: 'Future Bass Selections',
          cover_image: 'humanoid-2-0.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/3yXWBtDHv1q68Z9rPryu1k?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/3yXWBtDHv1q68Z9rPryu1k?si=df5f17b343574c20',
          },
          created_at: new Date(2021, 10, 12),
        },
        {
          id: '049',
          title: 'Confused',
          slug: 'confused',
          description: '',
          artist: 'sumthin sumthin, JAWNZA',
          album: 'Confused',
          playlist: 'Future Bass Selections',
          cover_image: 'confused.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/60b22qPABmxbX2Hox2MFqf?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/60b22qPABmxbX2Hox2MFqf?si=9a4e5c01df944a87',
          },
          created_at: new Date(2021, 10, 12),
        },
      ]
    },
    {
      id: 'P005',
      name: 'Hip Hop Selections',
      slug: 'hip-hop-selections',
      cover_image: 'hip-hop-selections.webp',
      songs: [{
          id: '039',
          title: 'Astronaut In The Ocean',
          slug: 'astronaut-in-the-ocean',
          description: '',
          artist: 'Masked Wolf',
          album: 'Astronaut In The Ocean',
          playlist: 'Hip Hop Selections',
          cover_image: 'astronaut-in-the-ocean.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/3Ofmpyhv5UAQ70mENzB277?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/3Ofmpyhv5UAQ70mENzB277?si=6f590d0622244aaa',
          },
          created_at: new Date(2021, 10, 11),
        },
        {
          id: '040',
          title: 'HOLIDAY',
          slug: 'holiday',
          description: '',
          artist: 'Lil Nas X',
          album: 'HOLIDAY',
          playlist: 'Hip Hop Selections',
          cover_image: 'holiday.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/6zFMeegAMYQo0mt8rXtrli?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/6zFMeegAMYQo0mt8rXtrli?si=394fd5a5b920484a',
          },
          created_at: new Date(2021, 10, 11),
        },
        {
          id: '041',
          title: 'CLOUDS',
          slug: 'clouds',
          description: '',
          artist: 'NF',
          album: 'CLOUDS (THE MIXTAPE)',
          playlist: 'Hip Hop Selections',
          cover_image: 'clouds.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/1mvI5pGoh84IiFSbWxEkGH?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/1mvI5pGoh84IiFSbWxEkGH?si=229ccea570a943af',
          },
          created_at: new Date(2021, 10, 11),
        },
        {
          id: '042',
          title: 'The Search',
          slug: 'the-search',
          description: '',
          artist: 'NF',
          album: 'The Search',
          playlist: 'Hip Hop Selections',
          cover_image: 'the-search.webp',
          spotify_embed_src: 'https://open.spotify.com/embed/track/3oLe5ZILASG8vU5dxIMfLY?utm_source=generator',
          link: {
            spotify: 'https://open.spotify.com/track/3oLe5ZILASG8vU5dxIMfLY?si=f2358c39209d4625',
          },
          created_at: new Date(2021, 10, 11),
        },
      ]
    },
    {
      id: 'P006',
      name: 'Techno Selections',
      slug: 'techno-selections',
      cover_image: 'techno-selections.webp',
      songs: [{
        id: '035',
        title: 'Shimmer',
        slug: 'shimmer',
        description: '',
        artist: 'Groovetique, Prove Them Wrong',
        album: 'Sands of Time',
        playlist: 'Techno Selections',
        cover_image: 'shimmer.webp',
        spotify_embed_src: 'https://open.spotify.com/embed/track/4Uet0CtqZex6iZmTKwWyKT?utm_source=generator',
        link: {
          spotify: 'https://open.spotify.com/track/4Uet0CtqZex6iZmTKwWyKT?si=7c391ce1075b4edd',
        },
        created_at: new Date(2021, 10, 12),
      }, ]
    },
  ],
})

export const getters = {}

export const mutations = {}
