export const state = () => ({
  list: [{
      id: '001',
      title: 'Energetic Stability - Vanita Remix',
      slug: 'energetic-stability',
      description: '',
      artist: 'Jeancy, Vanita',
      album: 'Inner Awen Vol. IV',
      playlist: 'Apsara Selections for Nusountara',
      cover_image: 'energetic-stability.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/7zMpjwJXj3tDOuKYfHYXV9?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/7zMpjwJXj3tDOuKYfHYXV9?si=96ebf169c2344016',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '002',
      title: 'Hybrid Society',
      slug: 'hybrid-society',
      description: '',
      artist: 'Matthias Meyer, Budakid',
      album: 'Sweet Ease / Hybrid Society',
      playlist: 'Apsara Selections for Nusountara',
      cover_image: 'hybrid-society.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/36UcjzLY5OC9Zhh8wIxobk?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/36UcjzLY5OC9Zhh8wIxobk?si=4586471d608a44af',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '003',
      title: 'Isolated',
      slug: 'isolated',
      description: '',
      artist: 'Zalvador',
      album: 'Isolated',
      playlist: 'Apsara Selections for Nusountara',
      cover_image: 'isolated.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/2TsoBkPWVBYZIoLAeJKOsD?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/2TsoBkPWVBYZIoLAeJKOsD?si=1fb1e4cf7d06429d',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '004',
      title: 'Manolito - Mixed',
      slug: 'manolito-mixed',
      description: '',
      artist: 'Marc DePulse',
      album: 'Ian Ludvig',
      playlist: 'Apsara Selections for Nusountara',
      cover_image: 'manolito-mixed.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/43X9vPylgkBqyN5Fo12bqo?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/43X9vPylgkBqyN5Fo12bqo?si=7083463b5c4b4ecc',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '005',
      title: 'Codetta - Original Mix',
      slug: 'codetta',
      description: '',
      artist: 'Ian Ludvig',
      album: 'Out of Time',
      playlist: 'Apsara Selections for Nusountara',
      cover_image: 'codetta.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/76aNLKn7Vx1ylDmcYrBitH?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/76aNLKn7Vx1ylDmcYrBitH?si=156da922aa31471f',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '006',
      title: 'Two Steps Ahead',
      slug: 'two-steps-ahead',
      description: '',
      artist: 'CJ Jeff, Robert Owens',
      album: 'Two Steps Ahead',
      playlist: 'Apsara Selections for Nusountara',
      cover_image: 'two-steps-ahead.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/7mjFKeu3WsafOkDecS0AVL?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/7mjFKeu3WsafOkDecS0AVL?si=68e382d07c6247d9',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '007',
      title: 'Alea',
      slug: 'alea',
      description: '',
      artist: 'Coeus',
      album: 'Alea',
      playlist: 'Apsara Selections for Nusountara',
      cover_image: 'alea.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/7u7ZbUU8SdNVlCQUNnt5Vn?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/7u7ZbUU8SdNVlCQUNnt5Vn?si=63419a3ee37b44b8',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '008',
      title: 'Axiom - Mixed',
      slug: 'axiom',
      description: '',
      artist: 'Erhan Kesen',
      album: 'THIS IS HOW WE DANTZE',
      playlist: 'Apsara Selections for Nusountara',
      cover_image: 'axiom.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/7ee6zNJRwQqxa9DNwiq7eo?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/7ee6zNJRwQqxa9DNwiq7eo?si=7870a44ab13842ae',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '009',
      title: 'Cordial',
      slug: 'cordial',
      description: '',
      artist: 'Arnas D, Lake Avalon',
      album: 'Stil vor Talent 300, Pt. 1',
      playlist: 'Apsara Selections for Nusountara',
      cover_image: 'cordial.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/3BHwBivzXUpmw3oaxXy56c?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/3BHwBivzXUpmw3oaxXy56c?si=8cce79bd71954a83',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '010',
      title: 'Clocks',
      slug: 'clocks',
      description: '',
      artist: 'Adana Twins, Kraków Loves Adana',
      album: '1983',
      playlist: 'Apsara Selections for Nusountara',
      cover_image: 'clocks.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/4DHrmGKXFNXQsprnIB7i2M?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/4DHrmGKXFNXQsprnIB7i2M?si=7325e7a89bf148ef',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '011',
      title: 'Korrado',
      slug: 'korrado',
      description: '',
      artist: 'Matador',
      album: 'Kingswing',
      playlist: 'Apsara Selections for Nusountara',
      cover_image: 'korrado.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/3l01TC0GrUnZAZvazUjYYz?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/3l01TC0GrUnZAZvazUjYYz?si=2f512b14a2a0449a',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '012',
      title: 'Ringo - Original Mix',
      slug: 'ringo',
      description: '',
      artist: 'Joris Voorn',
      album: 'Armada Chill 001',
      playlist: 'Apsara Selections for Nusountara',
      cover_image: 'ringo.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/6hjLUtZDHJ5GSDXwuMVJpr?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/6hjLUtZDHJ5GSDXwuMVJpr?si=59bd558826304028',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '013',
      title: 'Go',
      slug: 'go',
      description: '',
      artist: 'Moby',
      album: 'Moby',
      playlist: 'Apsara Selections for Nusountara',
      cover_image: 'go.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/6bzV0xGO4dROmmL9GmVkjM?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/6bzV0xGO4dROmmL9GmVkjM?si=0c85e2758c4047f2',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '014',
      title: 'After Dark',
      slug: 'after-dark',
      description: '',
      artist: 'Apsara',
      album: 'After Dark',
      playlist: 'Apsara Selections for Nusountara',
      cover_image: 'after-dark.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/5RXktsjbcCo4oxh8jIsCG5?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/5RXktsjbcCo4oxh8jIsCG5?si=4595a1320f4b45eb',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '015',
      title: 'Leap Year',
      slug: 'leap-year',
      description: '',
      artist: 'Steve Self',
      album: 'Shutter Shadow',
      playlist: 'Apsara Selections for Nusountara',
      cover_image: 'leap-year.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/0w7VZpWbF029Fe1R7KLjpC?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/0w7VZpWbF029Fe1R7KLjpC?si=44bc3a67c8b54dbd',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '016',
      title: 'Global Illumination',
      slug: 'global-illumination',
      description: '',
      artist: 'Liquid Soul',
      album: 'Love in Stereo',
      playlist: 'Apsara Selections for Nusountara',
      cover_image: 'global-illumination.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/5pGJCUcJPFDu9JO62t676u?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/5pGJCUcJPFDu9JO62t676u?si=9bb0d0768bf44a62',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '017',
      title: 'Carnaval - Superpitcher Main Fix',
      slug: 'carnaval-superpitcher',
      description: '',
      artist: 'STUDIO MULE, Superpitcher',
      album: 'Carnaval Superpitcher Remixes',
      playlist: 'Nandi Selections for Nusountara',
      cover_image: 'carnaval-superpitcher.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/4sphhYvjapufTnaEtNzmeM?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/4sphhYvjapufTnaEtNzmeM?si=a09d197abc714de6',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '018',
      title: 'Deichkind - Autonom - Dixon Edit',
      slug: 'deichkind-autonom',
      description: '',
      artist: 'Dixon',
      album: 'Deichkind - Autonom - Dixon Edit',
      playlist: 'Nandi Selections for Nusountara',
      cover_image: 'deichkind-autonom.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/7wkwJ9b1MD6KWJxn1Hmfct?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/7wkwJ9b1MD6KWJxn1Hmfct?si=f990c3d772a04cdb',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '019',
      title: 'Trans Afro Express - Instrumental',
      slug: 'trans-afro-express',
      description: '',
      artist: 'Jerome Sydenham, Fatima Njai, Mario Punchard',
      album: 'Trans Afro Express',
      playlist: 'Nandi Selections for Nusountara',
      cover_image: 'trans-afro-express.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/372dFgiZm21u1kkqfDlfmj?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/372dFgiZm21u1kkqfDlfmj?si=affd97313359416c',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '020',
      title: 'Alcatraz - Jimpster Dub',
      slug: 'alcatraz-jimpster-dub',
      description: '',
      artist: 'Kasper Bjørke, Jacob Bellens, Jimpster',
      album: 'Alcatraz',
      playlist: 'Nandi Selections for Nusountara',
      cover_image: 'alcatraz-jimpster-dub.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/4z0WPGHhXDzBXlzIRf4ZCS?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/4z0WPGHhXDzBXlzIRf4ZCS?si=329346e26ed54665',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '021',
      title: 'Cute & Freaky - Archie Hamilton Remix',
      slug: 'cute-and-freaky',
      description: '',
      artist: 'AJ Christou, Archie Hamilton',
      album: 'Cute & Freaky',
      playlist: 'Nandi Selections for Nusountara',
      cover_image: 'cute-and-freaky.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/3ES2ENCNr0gc9pgZSujShx?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/3ES2ENCNr0gc9pgZSujShx?si=deefcb35e91b49e3',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '022',
      title: 'Erotic Soul - Sensoreal Remix',
      slug: 'erotic-soul',
      description: '',
      artist: 'Gorge, Sensoreal',
      album: 'Erotic Soul 2020',
      playlist: 'Nandi Selections for Nusountara',
      cover_image: 'erotic-soul.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/6hdBZ3ncmfDY3gXAsj1Xea?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/6hdBZ3ncmfDY3gXAsj1Xea?si=62c0799b92fc4f0c',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '023',
      title: 'Introspection - Nick Curly Remix',
      slug: 'introspection',
      description: '',
      artist: 'Audiojack, Polarbear (UK), Nick Curly',
      album: 'Introspection',
      playlist: 'Nandi Selections for Nusountara',
      cover_image: 'introspection.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/1um2IN9kPFAXubWI2gOka8?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/1um2IN9kPFAXubWI2gOka8?si=4eda763b3b574167',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '024',
      title: 'Keeping Me Up',
      slug: 'keeping-me-up',
      description: '',
      artist: '9th House',
      album: 'Keeping Me Up',
      playlist: 'Nandi Selections for Nusountara',
      cover_image: 'keeping-me-up.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/7aaiDHS4bKCWF68WG5w4RY?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/7aaiDHS4bKCWF68WG5w4RY?si=fe486551a7a34984',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '025',
      title: 'How\'s The Music - (Go Higher Mix) [Harry Romero Edit]',
      slug: 'hows-the-music',
      description: '',
      artist: 'Winx, Josh Wink',
      album: 'How\'s The Music - (Go Higher Mix) [Harry Romero Edit]',
      playlist: 'Nandi Selections for Nusountara',
      cover_image: 'hows-the-music.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/5UMeRnwkZVlA65g2OY6JWU?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/5UMeRnwkZVlA65g2OY6JWU?si=16b17e3ffc284756',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '026',
      title: 'Træns 4',
      slug: 'traen-4',
      description: '',
      artist: 'Prins Thomas',
      album: 'Træns',
      playlist: 'Nandi Selections for Nusountara',
      cover_image: 'traen-4.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/1oKzJFNfc3kzKlLze71vqx?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/1oKzJFNfc3kzKlLze71vqx?si=50ab78cdb3ec459e',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '027',
      title: 'Omnibus',
      slug: 'omnibus',
      description: '',
      artist: 'Henrik Schwarz',
      album: 'Together EP',
      playlist: 'Nandi Selections for Nusountara',
      cover_image: 'omnibus.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/3cG82yEZda7ISsAz4ww8Wn?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/3cG82yEZda7ISsAz4ww8Wn?si=66d8d3e5ae0748b4',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '028',
      title: 'Can You Feel It',
      slug: 'can-you-feel-it',
      description: '',
      artist: 'Mr. Fingers',
      album: 'Four Most Cuts Presents - Mr. Fingers',
      playlist: 'Nandi Selections for Nusountara',
      cover_image: 'can-you-feel-it.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/5BK37zwHDS5UvE3Yh0JO8n?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/5BK37zwHDS5UvE3Yh0JO8n?si=db3b219637fb4504',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '029',
      title: 'I\'ll Be Your Friend - Original Mix (2011 Remastered Version)',
      slug: 'ill-be-your-friend',
      description: '',
      artist: 'Robert Owens',
      album: 'I\'ll Be Your Friend',
      playlist: 'Nandi Selections for Nusountara',
      cover_image: 'ill-be-your-friend.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/5SMnHUNB2iBm3rkuoHpIZO?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/5SMnHUNB2iBm3rkuoHpIZO?si=af047ca917a44a0a',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '030',
      title: 'Move Your Body',
      slug: 'move-your-body',
      description: '',
      artist: 'Marshall Jefferson, Solardo',
      album: 'Move Your Body',
      playlist: 'Nandi Selections for Nusountara',
      cover_image: 'move-your-body.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/3YXIVMQLRRq2K7kxC7UYx6?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/3YXIVMQLRRq2K7kxC7UYx6?si=dd0cea5f65124044',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '031',
      title: 'Acid Tracks - 12" Version',
      slug: 'acid-tracks',
      description: '',
      artist: 'Phuture',
      album: 'Acid Tracks (Remastered)',
      playlist: 'Nandi Selections for Nusountara',
      cover_image: 'acid-tracks.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/5ga953YTjaurkXuGHFjrNk?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/5ga953YTjaurkXuGHFjrNk?si=980d5e9c2cd146cd',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '032',
      title: 'Your Love (feat. Jamie Principle)',
      slug: 'your-love',
      description: '',
      artist: 'Frankie Knuckles, Jamie Principle',
      album: 'Four Most Cuts Presents',
      playlist: 'Nandi Selections for Nusountara',
      cover_image: 'your-love.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/6tvtFyEdNpeurBkT2zNMEL?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/6tvtFyEdNpeurBkT2zNMEL?si=cab2787f22ed4594',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '033',
      title: 'The Bounce',
      slug: 'the-bounce',
      description: '',
      artist: 'KenLou',
      album: 'II: The Bounce / Gimme Groove',
      playlist: 'Nandi Selections for Nusountara',
      cover_image: 'the-bounce.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/30y6AIWDz0xop8Vtfn2EyM?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/30y6AIWDz0xop8Vtfn2EyM?si=135342a850034ff9',
      },
      created_at: new Date(2021, 9, 17),
    },
    {
      id: '034',
      title: 'The Damned - 2021 Raw Edit',
      slug: 'the-damned',
      description: '',
      artist: 'Baime',
      album: 'The Damned (Remixed)',
      playlist: 'Melodic House Selections for Nusountara',
      cover_image: 'the-damned.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/0bJnPgVQahV5MwMGHdq4WH?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/0bJnPgVQahV5MwMGHdq4WH?si=d6a9543ac1a94679',
      },
      created_at: new Date(2021, 9, 20),
    },
    {
      id: '035',
      title: 'Shimmer',
      slug: 'shimmer',
      description: '',
      artist: 'Groovetique, Prove Them Wrong',
      album: 'Sands of Time',
      playlist: 'Melodic House Selections for Nusountara',
      cover_image: 'shimmer.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/4Uet0CtqZex6iZmTKwWyKT?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/4Uet0CtqZex6iZmTKwWyKT?si=0b94704e771d4c51',
      },
      created_at: new Date(2021, 10, 12),
    },
    {
      id: '036',
      title: 'Enigma',
      slug: 'enigma',
      description: '',
      artist: 'Moonwalk',
      album: 'Solaris - EP',
      playlist: 'Melodic House Selections for Nusountara',
      cover_image: 'enigma.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/3RhoJBbU3aXy4hO9cFQZEL?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/3RhoJBbU3aXy4hO9cFQZEL?si=4b3681febd7e4dc7',
      },
      created_at: new Date(2021, 10, 12),
    },
    {
      id: '037',
      title: 'Space Odyssey',
      slug: 'space-odyssey',
      description: '',
      artist: 'Pavel Khvaleev',
      album: 'Space Odyssey',
      playlist: 'Melodic House Selections for Nusountara',
      cover_image: 'space-odyssey.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/0tWJ9VRKIjuJrsiTbBhMhi?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/0tWJ9VRKIjuJrsiTbBhMhi?si=484ece21017248a2',
      },
      created_at: new Date(2021, 10, 12),
    },
    {
      id: '038',
      title: 'Mercy Falls',
      slug: 'mercy-falls',
      description: '',
      artist: 'CharlestheFirst',
      album: 'The Reach EP',
      playlist: 'Future Bass Selections',
      cover_image: 'mercy-falls.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/6oSxm8jKgVbrlKo4Ktd1qr?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/6oSxm8jKgVbrlKo4Ktd1qr?si=c976d01e125842b6',
      },
      created_at: new Date(2021, 10, 11),
    },
    {
      id: '039',
      title: 'Astronaut In The Ocean',
      slug: 'astronaut-in-the-ocean',
      description: '',
      artist: 'Masked Wolf',
      album: 'Astronaut In The Ocean',
      playlist: 'Hip Hop Selections',
      cover_image: 'astronaut-in-the-ocean.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/3Ofmpyhv5UAQ70mENzB277?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/3Ofmpyhv5UAQ70mENzB277?si=6f590d0622244aaa',
      },
      created_at: new Date(2021, 10, 11),
    },
    {
      id: '040',
      title: 'HOLIDAY',
      slug: 'holiday',
      description: '',
      artist: 'Lil Nas X',
      album: 'HOLIDAY',
      playlist: 'Hip Hop Selections',
      cover_image: 'holiday.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/6zFMeegAMYQo0mt8rXtrli?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/6zFMeegAMYQo0mt8rXtrli?si=394fd5a5b920484a',
      },
      created_at: new Date(2021, 10, 11),
    },
    {
      id: '041',
      title: 'CLOUDS',
      slug: 'clouds',
      description: '',
      artist: 'NF',
      album: 'CLOUDS (THE MIXTAPE)',
      playlist: 'Hip Hop Selections',
      cover_image: 'clouds.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/1mvI5pGoh84IiFSbWxEkGH?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/1mvI5pGoh84IiFSbWxEkGH?si=229ccea570a943af',
      },
      created_at: new Date(2021, 10, 11),
    },
    {
      id: '042',
      title: 'The Search',
      slug: 'the-search',
      description: '',
      artist: 'NF',
      album: 'The Search',
      playlist: 'Hip Hop Selections',
      cover_image: 'the-search.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/3oLe5ZILASG8vU5dxIMfLY?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/3oLe5ZILASG8vU5dxIMfLY?si=f2358c39209d4625',
      },
      created_at: new Date(2021, 10, 11),
    },
    {
      id: '043',
      title: 'Dark Crystal - Pigeon Hole Remix',
      slug: 'dark-crystal',
      description: '',
      artist: 'Minnesota, Pigeon Hole',
      album: 'Curio Remixes',
      playlist: 'Future Bass Selections',
      cover_image: 'dark-crystal.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/1YJF87L1gBY6vpiOQGUaX5?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/1YJF87L1gBY6vpiOQGUaX5?si=7165454a21244acb',
      },
      created_at: new Date(2021, 10, 12),
    },
    {
      id: '044',
      title: 'Oni',
      slug: 'oni',
      description: '',
      artist: 'Champagne Drip',
      album: 'Of Course I Still Love You',
      playlist: 'Future Bass Selections',
      cover_image: 'oni.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/2YonNPsOfBszCc1UvVCdn7?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/2YonNPsOfBszCc1UvVCdn7?si=320d0d9b5fbb4b74',
      },
      created_at: new Date(2021, 10, 12),
    },
    {
      id: '045',
      title: 'Kaleidoscope (Feat. Crystalline)',
      slug: 'kaleidoscope',
      description: '',
      artist: 'Champagne Drip, Crystalline',
      album: 'Starman',
      playlist: 'Future Bass Selections',
      cover_image: 'kaleidoscope.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/10dLRZ7GCIXEuUuONkNcxI?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/10dLRZ7GCIXEuUuONkNcxI?si=0231dda19dfd408e',
      },
      created_at: new Date(2021, 10, 12),
    },
    {
      id: '046',
      title: 'Hmu (feat. Clay Parnell & Rory \"Sweet Boy\" Dolan)',
      slug: 'hmu',
      description: '',
      artist: 'Space Jesus, Clay Parnell, Rory \"Sweet Boy\" Dolan',
      album: 'Atom + Eve',
      playlist: 'Future Bass Selections',
      cover_image: 'hmu.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/5F3t5WgLyBX2W7un8IXiLD?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/5F3t5WgLyBX2W7un8IXiLD?si=0ad5a2ddd65e4ceb',
      },
      created_at: new Date(2021, 10, 12),
    },
    {
      id: '047',
      title: 'Speaking in Tongues',
      slug: 'speaking-in-tongues',
      description: '',
      artist: 'Jade Cicada',
      album: 'Brood VII',
      playlist: 'Future Bass Selections',
      cover_image: 'speaking-in-tongues.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/1eMMDk4yBBNuxyqSINu6ti?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/1eMMDk4yBBNuxyqSINu6ti?si=b2b246a14c364af4',
      },
      created_at: new Date(2021, 10, 12),
    },
    {
      id: '048',
      title: 'Humanoid 2.0',
      slug: 'humanoid-2-0',
      description: '',
      artist: 'Eprom, ZEKE BEATS',
      album: 'Humanoid 2.0',
      playlist: 'Future Bass Selections',
      cover_image: 'humanoid-2-0.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/3yXWBtDHv1q68Z9rPryu1k?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/3yXWBtDHv1q68Z9rPryu1k?si=df5f17b343574c20',
      },
      created_at: new Date(2021, 10, 12),
    },
    {
      id: '049',
      title: 'Confused',
      slug: 'confused',
      description: '',
      artist: 'sumthin sumthin, JAWNZA',
      album: 'Confused',
      playlist: 'Future Bass Selections',
      cover_image: 'confused.webp',
      spotify_embed_src: 'https://open.spotify.com/embed/track/60b22qPABmxbX2Hox2MFqf?utm_source=generator',
      link: {
        spotify: 'https://open.spotify.com/track/60b22qPABmxbX2Hox2MFqf?si=9a4e5c01df944a87',
      },
      created_at: new Date(2021, 10, 12),
    },
    {
      title: 'Midnight in Peckham',
      slug: 'midnight-in-peckham',
      artist: 'Chaos in the CBD',
      genres: ['house'],
      playlist: 'Top Charts',
      cover_image: 'Midnight in Peckham.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/1CzfZY7lXaysy84x3a2jix?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/1CzfZY7lXaysy84x3a2jix?si=a0d8071da3e64cdc',
      },
    },
    {
      title: 'Set It Out',
      slug: 'set-it-out',
      artist: 'Omar S',
      genres: ['house'],
      playlist: 'Top Charts',
      cover_image: 'Set It Out.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/55uBEgwtpTx5NGgzkoDoAx?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/55uBEgwtpTx5NGgzkoDoAx?si=cb86549824ee47d2',
      },
    },
    {
      title: 'Selfless State',
      slug: 'selfless-state',
      artist: 'So Inagawa',
      genres: ['house'],
      playlist: 'Top Charts',
      cover_image: 'Selfless State.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/playlist/1oc323dm0734ZasBpqQGou?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/playlist/1oc323dm0734ZasBpqQGou?si=09892a3dbefb4a68',
      },
    },
    {
      title: 'Footwork',
      slug: 'footwork',
      artist: 'Theo Parrish',
      genres: ['house'],
      playlist: 'Top Charts',
      cover_image: 'Footwork.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/2m7DFd2aOXVpNlA5KeAlA7?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/2m7DFd2aOXVpNlA5KeAlA7?si=5459776b49324d31',
      },
    },
    {
      title: '3D Print',
      slug: '3d-print',
      artist: 'DJ Sneak',
      genres: ['house'],
      playlist: 'Top Charts',
      cover_image: '3D Print.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/5gp6c8VfyXDQLwu9arBvSe?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/5gp6c8VfyXDQLwu9arBvSe?si=785325fed9194ac3',
      },
    },
    {
      title: 'It\'s Over Love',
      slug: 'its-over-love',
      artist: 'Todd Terry',
      genres: ['house'],
      playlist: 'Top Charts',
      cover_image: 'It\'s Over Love.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/3t2DaDCFAj6ko9RFQxvyaA?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/3t2DaDCFAj6ko9RFQxvyaA?si=794666bb402a4c5a',
      },
    },
    {
      title: 'The Way You Like',
      slug: 'the-way-you-like',
      artist: 'Gene Farris',
      genres: ['house'],
      playlist: 'Top Charts',
      cover_image: 'The Way You Like.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/0Sw5puLByGkHnj4EQGjIcx?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/0Sw5puLByGkHnj4EQGjIcx?si=2b3713806ee94788',
      },
    },
    {
      title: 'Who\'s Afraid of Detroit',
      slug: 'who-is-afraid-of-detroit',
      artist: 'Claude VonStroke',
      genres: ['house'],
      playlist: 'Top Charts',
      cover_image: 'Who\'s Afraid of Detroit.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/1KiNEbmfe20LO0jitOp8Ao?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/1KiNEbmfe20LO0jitOp8Ao?si=7ef4357d76eb4246',
      },
    },
    {
      title: 'Get on Down',
      slug: 'get-on-down',
      artist: 'Kenny Dope',
      genres: ['house'],
      playlist: 'Top Charts',
      cover_image: 'Get on Down.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/4PEdxcK7pPL6TWM0lUSh5K?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/4PEdxcK7pPL6TWM0lUSh5K?si=89d6177fc3c24d3c',
      },
    },
    {
      title: 'Believe',
      slug: 'believe',
      artist: 'Fred Everything',
      genres: ['house'],
      playlist: 'Top Charts',
      cover_image: 'Believe.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/14WqqgfrkNvD9ll7DBUsvl?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/14WqqgfrkNvD9ll7DBUsvl?si=df6b698312cc483f',
      },
    },
    {
      title: 'True Lies',
      slug: 'true-lies',
      artist: 'Setaoc Mass',
      genres: ['techno'],
      playlist: 'Top Charts',
      cover_image: 'True Lies.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/2WobLGO7SSVTNGK5ZHX6ru?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/2WobLGO7SSVTNGK5ZHX6ru?si=bf93706f45ad43fd',
      },
    },
    {
      title: 'Horses on Acid',
      slug: 'horses-on-acid',
      artist: 'Rove Ranger',
      genres: ['techno'],
      playlist: 'Top Charts',
      cover_image: 'Horses on Acid.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/4CEYSWaDxJ7u5jBG6nPljt?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/4CEYSWaDxJ7u5jBG6nPljt?si=d497215c51eb44c4',
      },
    },
    {
      title: 'It\'s Time Again',
      slug: 'its-time-again',
      artist: 'Fjaak',
      genres: ['techno'],
      playlist: 'Top Charts',
      cover_image: 'It\'s Time Again.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/6OrQScHNkYMIt5597o51xr?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/6OrQScHNkYMIt5597o51xr?si=01b646204a694ac1',
      },
    },
    {
      title: 'Scrapes',
      slug: 'scrapes',
      artist: 'Raär',
      genres: ['techno'],
      playlist: 'Top Charts',
      cover_image: 'Scrapes.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/4BcSXxKBSazBfsmjNhUuPv?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/4BcSXxKBSazBfsmjNhUuPv?si=83091682d7fa452c',
      },
    },
    {
      title: 'It Should Be Working',
      slug: 'it-should-be-working',
      artist: 'Nørbak',
      genres: ['techno'],
      playlist: 'Top Charts',
      cover_image: 'It Should Be Working.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/3F3K9N4JVeEV0XKBDnhY4O?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/3F3K9N4JVeEV0XKBDnhY4O?si=f734609c78044392',
      },
    },
    {
      title: 'Missing You',
      slug: 'missing-you',
      artist: 'Neil Landstrumm',
      genres: ['techno'],
      playlist: 'Top Charts',
      cover_image: 'Missing You.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/0LZshnM1Awtayy5yeE7pg4?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/0LZshnM1Awtayy5yeE7pg4?si=80e3ced8ff4b4f23',
      },
    },
    {
      title: 'Orbital',
      slug: 'orbital',
      artist: 'Rebekah',
      genres: ['techno'],
      playlist: 'Top Charts',
      cover_image: 'Orbital.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/2VJ23tiaQryzDmt6NdioQG?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/2VJ23tiaQryzDmt6NdioQG?si=b1f5194070fc448e',
      },
    },
    {
      title: 'Blue Mood',
      slug: 'blue-mood',
      artist: 'Stanislav Tolkachev',
      genres: ['techno'],
      playlist: 'Top Charts',
      cover_image: 'Blue Mood.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/1mJMWzf9znNiAGBkByO0mi?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/1mJMWzf9znNiAGBkByO0mi?si=819dd8ba4929436b',
      },
    },
    {
      title: 'Stolen',
      slug: 'stolen',
      artist: 'DJ Justin Johnson, 3PO, Len Faki',
      genres: ['techno'],
      playlist: 'Top Charts',
      cover_image: 'Stolen.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/75FI4n4uQZMBG9m7KSUJOd?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/75FI4n4uQZMBG9m7KSUJOd?si=305e30402a1f4543',
      },
    },
    {
      title: 'Protech the Skyline',
      slug: 'protech-the-skyline',
      artist: 'Ecilo',
      genres: ['techno'],
      playlist: 'Top Charts',
      cover_image: 'Protech the Skyline.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/3SlDrLPXX9iFN9TNsRKovi?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/3SlDrLPXX9iFN9TNsRKovi?si=1b79fc5204ca4ea6',
      },
    },
    {
      title: 'Tornado Alley',
      slug: 'tornado-alley',
      artist: 'Pablo Bozzi',
      genres: ['dark-disco'],
      playlist: 'Top Charts',
      cover_image: 'tornado-alley.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/0tK4NGN357N0JcH17lW3PW?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/0tK4NGN357N0JcH17lW3PW?si=0a05395eb007411d',
      },
    },
    {
      title: 'U-Shield',
      slug: 'u-shield',
      artist: 'Surfface',
      genres: ['dark-disco'],
      playlist: 'Top Charts',
      cover_image: 'u-shield.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/3YnHLknxeinvDF8bsq2Kbf?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/3YnHLknxeinvDF8bsq2Kbf?si=969e6d582fe44cea',
      },
    },
    {
      title: 'Dark Energy',
      slug: 'dark-energy',
      artist: 'Cyda',
      genres: ['dark-disco'],
      playlist: 'Top Charts',
      cover_image: 'dark-energy.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/3cy9KxeCN0XLMXQaBJHXHC?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/3cy9KxeCN0XLMXQaBJHXHC?si=045940c30d7044aa',
      },
    },
    {
      title: 'Gozanlove',
      slug: 'gozanlove',
      artist: 'Cardo V',
      genres: ['dark-disco'],
      playlist: 'Top Charts',
      cover_image: 'gozanlove.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/3cy9KxeCN0XLMXQaBJHXHC?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/3aKOszob8AYVGTwXiCnYcV?si=071a0f58d1b14417',
      },
    },
    {
      title: 'Being Boring',
      slug: 'being-boring',
      artist: 'Chinaski',
      genres: ['dark-disco'],
      playlist: 'Top Charts',
      cover_image: 'being-boring.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/6l4uu2OdSQ8ftDm2jtWzZC?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/6l4uu2OdSQ8ftDm2jtWzZC?si=300bafc0b873438f',
      },
    },
    {
      title: 'Blood Oath',
      slug: 'blood-oath',
      artist: 'Curses',
      genres: ['dark-disco'],
      playlist: 'Top Charts',
      cover_image: 'blood-oath.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/5KRa8Uhskz5XLmrd7eJ62v?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/5KRa8Uhskz5XLmrd7eJ62v?si=dfa2d5f13fca4c98',
      },
    },
    {
      title: 'El Wild',
      slug: 'el-wild',
      artist: 'Zombies in Miami',
      genres: ['dark-disco'],
      playlist: 'Top Charts',
      cover_image: 'el-wild.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/6fnVF4faS4wZ1jTfcJAWJC?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/6fnVF4faS4wZ1jTfcJAWJC?si=a566f083b7334245',
      },
    },
    {
      title: '4am in Parga Street',
      slug: '4am-in-parga-street',
      artist: 'Infravision',
      genres: ['dark-disco'],
      playlist: 'Top Charts',
      cover_image: '4am-in-parga-street.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/58ZiVVGRiqrINXsRkV4FAo?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/58ZiVVGRiqrINXsRkV4FAo?si=6c52db2415114391',
      },
    },
    {
      title: 'Guinness Italo',
      slug: 'guinness-italo',
      artist: 'David Jackson',
      genres: ['dark-disco'],
      playlist: 'Top Charts',
      cover_image: 'guinness-italo.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/30tW828ytHHvbTFAi8MTjY?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/30tW828ytHHvbTFAi8MTjY?si=7c400a1a54c140ad',
      },
    },
    {
      title: 'Do You Read Me?',
      slug: 'do-you-read-me',
      artist: 'Biesmans',
      genres: ['dark-disco'],
      playlist: 'Top Charts',
      cover_image: 'do-you-read-me.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/5NAV1u4MxGBB4UMATg8oLF?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/5NAV1u4MxGBB4UMATg8oLF?si=d7e253db3f904985',
      },
    },
    {
      title: 'Consciousness',
      slug: 'consciousness',
      artist: 'Anyma & Chris Avantgarde',
      genres: ['melodic-house-and-techno'],
      playlist: 'Top Charts',
      cover_image: 'consciousness.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/1DOuZaf52j4O1zlyQpxSQx?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/1DOuZaf52j4O1zlyQpxSQx?si=f7038a46ac56418e',
      },
    },
    {
      title: 'Promotheus',
      slug: 'promotheus',
      artist: 'Avidus',
      genres: ['melodic-house-and-techno'],
      playlist: 'Top Charts',
      cover_image: 'promotheus.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/7sO0E7yfhhLjWoKOt4aZ7j?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/7sO0E7yfhhLjWoKOt4aZ7j?si=ec630abd8a6a422d',
      },
    },
    {
      title: 'Drown (Massano Remix)',
      slug: 'drown',
      artist: 'Øostil & Juan Hansen',
      genres: ['melodic-house-and-techno'],
      playlist: 'Top Charts',
      cover_image: 'drown.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/74oc8wSuilCIueLaqNOi3B?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/74oc8wSuilCIueLaqNOi3B?si=1ed6d5055c6f490a',
      },
    },
    {
      title: 'Loss of Hope',
      slug: 'loss-of-hope',
      artist: 'Innellea',
      genres: ['melodic-house-and-techno'],
      playlist: 'Top Charts',
      cover_image: 'loss-of-hope.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/5QRhs05R9MOXHQC2OOn5bq?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/5QRhs05R9MOXHQC2OOn5bq?si=bdf3bb7dc991409d',
      },
    },
    {
      title: 'Running (feat. Meg Myers) - Original Mix',
      slug: 'running',
      artist: 'Anyma, Meg Myers',
      genres: ['melodic-house-and-techno'],
      playlist: 'Top Charts',
      cover_image: 'running.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/6fbNKnzlcQzbtryQYSxpMb?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/6fbNKnzlcQzbtryQYSxpMb?si=0962dc65961b4329',
      },
    },
    {
      title: 'After Dark',
      slug: 'after-dark-apsara',
      artist: 'Apsara',
      genres: ['melodic-house-and-techno'],
      playlist: 'Top Charts',
      cover_image: 'after-dark.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/5RXktsjbcCo4oxh8jIsCG5?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/5RXktsjbcCo4oxh8jIsCG5?si=4a9171d8e77a4145',
      },
    },
    {
      title: 'Oxygen Level Low',
      slug: 'oxygen-level-low',
      artist: 'Colyn',
      genres: ['melodic-house-and-techno'],
      playlist: 'Top Charts',
      cover_image: 'oxygen-level-low.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/39U2Ryd4imSGCEOou6hy4W?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/39U2Ryd4imSGCEOou6hy4W?si=5860010ec8904da8',
      },
    },
    {
      title: 'Maya - Original Mix',
      slug: 'maya',
      artist: 'Tantra, Hudi Ardianto',
      genres: ['melodic-house-and-techno'],
      playlist: 'Top Charts',
      cover_image: 'maya.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/7enCohQry0Rr2R0dGMT16s?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/7enCohQry0Rr2R0dGMT16s?si=e2387af7f7b5498e',
      },
    },
    {
      title: 'Return to Oz (ARTBAT Remix)',
      slug: 'return-to-oz',
      artist: 'Monolink, ARTBAT',
      genres: ['melodic-house-and-techno'],
      playlist: 'Top Charts',
      cover_image: 'return-to-oz.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/0gwNGHcBRYtF7mvgUczVo1?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/0gwNGHcBRYtF7mvgUczVo1?si=82582a34d67b4e5d',
      },
    },
    {
      title: 'Last Roar',
      slug: 'last-roar',
      artist: 'Tuantigabelas, Rizal Tanmenan',
      genres: ['R&B-and-Hip-Hop'],
      playlist: 'Top Charts',
      cover_image: 'last-roar.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/1Xia6QzwhODVNSGoouc6UF?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/1Xia6QzwhODVNSGoouc6UF?si=fa16467e271b4b69',
      },
    },
    {
      title: 'CHING',
      slug: 'ching',
      artist: 'Basboi',
      genres: ['R&B-and-Hip-Hop'],
      playlist: 'Top Charts',
      cover_image: 'ching.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/6ZaGQezHQanrroD0TsgeMz?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/6ZaGQezHQanrroD0TsgeMz?si=4d6a061a30a742f7',
      },
    },
    {
      title: 'Pulang',
      slug: 'pulang',
      artist: 'Sendeljer',
      genres: ['R&B-and-Hip-Hop'],
      playlist: 'Top Charts',
      cover_image: 'pulang.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/4kIzic9rFHajN3orpZY1oV?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/4kIzic9rFHajN3orpZY1oV?si=29eb66f7c3de43c2',
      },
    },
    {
      title: 'edamame (feat. Rich Brian)',
      slug: 'edamame',
      artist: 'bbno$, Rich Brian',
      genres: ['R&B-and-Hip-Hop'],
      playlist: 'Top Charts',
      cover_image: 'edamame.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/1uMHCAyGmHqyygoNRuo7MV?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/1uMHCAyGmHqyygoNRuo7MV?si=c4952d1829934f48',
      },
    },
    {
      title: 'Knows Me Better',
      slug: 'knows-me-better',
      artist: 'Mario Zwinkle',
      genres: ['R&B-and-Hip-Hop'],
      playlist: 'Top Charts',
      cover_image: 'knows-me-better.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/7hMQgJKFaB5jckLA5hrPmp?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/7hMQgJKFaB5jckLA5hrPmp?si=fdb70a96fb514b29',
      },
    },
    {
      title: 'On My Mind',
      slug: 'on-my-mind',
      artist: 'Tuantigabelas',
      genres: ['R&B-and-Hip-Hop'],
      playlist: 'Top Charts',
      cover_image: 'on-my-mind.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/6E8ppVkvAHCOuZNSMrepxR?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/6E8ppVkvAHCOuZNSMrepxR?si=69b05335b9d342f3',
      },
    },
    {
      title: 'Real',
      slug: 'real',
      artist: 'Sonjah',
      genres: ['R&B-and-Hip-Hop'],
      playlist: 'Top Charts',
      cover_image: 'real.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/274IpKSvGZkde4VTSf0a7O?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/274IpKSvGZkde4VTSf0a7O?si=829ece96ee3d4687',
      },
    },
    {
      title: 'Kasih Naik',
      slug: 'kasih-naik',
      artist: 'Eltaro, Brayen MC',
      genres: ['R&B-and-Hip-Hop'],
      playlist: 'Top Charts',
      cover_image: 'kasih-naik.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/6c51hbEAxdqrGjO0uUae0p?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/6c51hbEAxdqrGjO0uUae0p?si=49b6b26bf4e346a5',
      },
    },
    {
      title: 'West Melasania',
      slug: 'west-melasania',
      artist: 'Keilandboi, Pedro',
      genres: ['R&B-and-Hip-Hop'],
      playlist: 'Top Charts',
      cover_image: 'west-melasania.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/01anhFiG7ji0Sh4n1FgMGO?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/01anhFiG7ji0Sh4n1FgMGO?si=2946d8dada6d47fe',
      },
    },
    {
      title: 'Kick It',
      slug: 'kick-it',
      artist: 'Muztang, Tuantigabelas, Tara, Indra Domdom',
      genres: ['R&B-and-Hip-Hop'],
      playlist: 'Top Charts',
      cover_image: 'kick-it.jpg',
      spotify_embed_src: 'https://open.spotify.com/embed/track/2oDNnADDk3iuXgBZmNCy28?utm_source=generator&theme=0',
      link: {
        spotify: 'https://open.spotify.com/track/2oDNnADDk3iuXgBZmNCy28?si=a21a0e6efe674cce',
      },
    },
  ],
})

export const getters = {}

export const mutations = {}
